export { default as Home } from "./Home/Home";
export { default as Cart } from "./Cart/Cart";
export { default as About } from "./About/About";
export { default as Contact } from "./Contact/Contact";
export { default as Collections } from "./Collections/Collections";
export { default as Login } from "./Login/Login";
export { default as Orders } from "./Orders/Orders";
export { default as PlaceOrder } from "./PlaceOrder/PlaceOrder";
export { default as Product } from "./Product/Product";
